name: gemini-ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          make install
      - name: Check import order with isort
        run: |
          make isort-check
      - name: Format code check with black
        run: |
          make black-check
      - name: Lint code with pylint
        run: |
          make lint-check
      - name: Type check code with mypy
        run: |
          make type-check
      - name: Test with pytest
        run: |
          make pytest
